### PR TITLE
Added 3 short .cpp programs.

### PR DESCRIPTION
**Pull request by kirti-pandey20**
Added 3 codes to-
1.Find GCD of 2 numbers.
2.Find number of divisors of a given number along with their sum.
3.Sieve of Eratosthenes.

### CODE REVIEW

**Review by PrajaktaSathe — CHANGES_REQUESTED** [review]
Good Work! I would like for you to make a small change in the PR. We just need the 3 files with the .cpp extension. Do not attach the file with the .exe and .o extension. Thanks!

**Comment by kirti-pandey20** [comment]
Sure . I will make the necessary changes right away.

**Review by PrajaktaSathe — APPROVED** [review]
Thanks for the changes! I will merge the PR now! 👍🏻

**Comment by kirti-pandey20** [comment]
Thanks a lot.

**Comment by PrajaktaSathe** [comment]
No problem! 😄 Happy coding!!

**Pull request merged**
